### ISSUE TITLE
Getting VideoDownloader's speed

### ISSUE THREAD

**Issue by UngarMax** [flagbug/YoutubeExtractor#117]
I would like to know if there is a way I could get the current speed of a VideoDownloader class which is actually downloading a file. It's for showing it up to a GUI, and I don't have any idea on how I could do that, since it isn't built-in. Does anybody know how to do that? Thanks in advance!

**Comment by Cyano** [comment]
When I was using this library on a project I was working on, this is how I did it.

Since Rate = (Information Received) / (Time Taken)

Create a variable that holds the time when the download 
`DateTime timeStart`


You'll need to work out how many bits have been downloaded out of the total number of bits.
In VideoDownloader.cs this is the 'copiedBytes' variable. You'll need to pass that amount to a function
inside the EventHandler ProgressEvent (ProgressEventArgs.cs)

Now every time the download progresses (ProgressEvent is fired) , call a function similar too:

	private double calculateTransferRate()
			{

				DateTime currentTime = DateTime.Now;
					
				double inSeconds = (currentTime - timeStart).TotalSeconds; //Time Elapsed
				
				double transferRate = (this.copiedBytes / inSeconds); //Speed = Distance / Time
				return transferRate;
				
			}
					
This will return a transferRate in bytes, you'll probably want that in a more human readable form using something
like http://stackoverflow.com/questions/281640/how-do-i-get-a-human-readable-file-size-in-bytes-abbreviation-using-net

Once you have the transferRate you can also calculate an ETA;

Time Remaining = (Information Remaining) / (Transfer Rate)

	private int calculateETA()
	{
		double tRate = calculateTransferRate();

		int etaTime = Convert.ToInt32((this.contentLength - this.copiedBytes) / tRate);
		return etaTime;
	}
	
This will return a value of the ETA in seconds, you'll probably want to format that into minutes & seconds (/60 and %60 respectively).

Then just return that information back to your GUI (could change the signature of ProgressEventArgs to achieve this)

**Comment by UngarMax** [comment]
Well, true thing: I could have just used logic to do that. Anyway thanks for the heads up and for this incredible implementation :) :+1:
