### ISSUE TITLE
Extracting the Youtube thumbnail

### ISSUE THREAD

**Issue by nightfrost** [flagbug/YoutubeExtractor#159]
Is there a way to do this, I've tried to run through the extract process but I cannot find it. I'm sorry if I'm asking the wrong place, as it really isn't an issue. It's my first ever question/doing on GitHub, bear with me :)

**Comment by flagbug** [comment]
Hi, please use the [official YouTube API](https://github.com/google/google-api-dotnet-client)  for this!

**Comment by dchurch2012** [comment]
Finding this error more frequently now:

Could not parse the Youtube page for URL http://youtube.com/watch?v=o9xFIiMAxK4
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues URL : https://www.youtube.com/watch?v=o9xFIiMAxK4

I am thinking it may involve the decryption algorithm?
