### ISSUE TITLE
Cannot get VEVO videos

### ISSUE THREAD

**Issue by new01bie** [flagbug/YoutubeExtractor#164]
I can't get urls of this video (VEVO): https://www.youtube.com/watch?v=YQHsXMglC9A
but this video is OK (not VEVO): https://www.youtube.com/watch?v=ZRmRamdNFHg

**Comment by flagbug** [comment]
Which version of YoutubeExtractor are you using?

**Comment by new01bie** [comment]
0.10.8

**Comment by RogerSchmidlin** [comment]
same here, same version

**Comment by RogerSchmidlin** [comment]
It actually worked this time but took 60 seconds. I tried before and it threw an exception. It also looks like it spawn quite a few threads during this process.

**Comment by RogerSchmidlin** [comment]
Tested with 0.10.9 => Vevo link retrieved after about 60 seconds, but doesn't play in MediaPlayer. Wondering if the fix for #167 is already in 0.10.9

Adele - Hello => VEVO => takes about one minute. This link doesn’t play in Android MediaPlayer
https://www.youtube.com/watch?v=YQHsXMglC9A

https://r5---sn-ppoxu-2xge.googlevideo.com:443/videoplayback?fexp=9416126,9419452,9420452,9420540,9422341,9422431,9422596,9423291,9423630,9423662,9423978,9424135,9426138,9426409&upn=dz9s_gkXsYc&itag=22&requiressl=yes&mime=video/mp4&ratebypass=yes&ipbits=0&expire=1451651149&sparams=dur,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&initcwndbps=836250&key=yt6&ip=124.148.122.23&pl=18&mn=sn-ppoxu-2xge&mm=31&ms=au&id=o-AMkA2nlUGv4as1MOVkR8T0swrlP8a697Yeqyw99UdaNb&mv=m&mt=1451629431&sver=3&dur=366.875&lmt=1445682343305162&source=youtube&signature=A3C9DD7F273A10C25D1F5EE2258D6FD8A9035AE1.882EE3ACAF91006C248F2392AD5AA5240B6C3F32&fallback_host=tc.v6.cache6.googlevideo.com


Everything works like a charm:
Lindy Hop funny instructional video : Groovie Movie (1944)
https://www.youtube.com/watch?v=i_ENjos_PpE

https://r4---sn-ppoxu-2xge.googlevideo.com/videoplayback?itag=18&upn=8Hkmkhz5Gkk&sver=3&signature=BF74DC98723BC7642652F6B8B8F40CE716F75AA8.2AE7B973B1C9FE2A599C5172A4FB12DB700BB84F&sparams=dur,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&mv=m&pl=18&ipbits=0&ms=au&source=youtube&expire=1451651658&mm=31&id=o-AJZGokOKyXG-FHVlk76cUT0kCBRXX664dw1tKkSfKV1_&mt=1451629972&mn=sn-ppoxu-2xge&ratebypass=yes&fexp=9407188,9408501,9414671,9416126,9418203,9420452,9420718,9422141,9422596,9423240,9423411,9423487,9423662,9424987,9425418,9425715,9426055&lmt=1429779768442027&dur=557.139&initcwndbps=840000&requiressl=yes&key=yt6&mime=video/mp4&ip=124.148.122.23

**Comment by RogerSchmidlin** [comment]
You published a new version 0.10.10. Still the same issue with loading these video files. The eventually but only after one minute. Any news on that? Unfortunately Android kills the app process after a certain time, different on different devices and versions.

**Comment by RogerSchmidlin** [comment]
Here is a different link that causes the same problem. I hope that helps:
https://www.youtube.com/watch?v=FrG4TEcSuRg
Let me know if I can help with anymore data. I can't fix the code but I am great in testing for you :-)

**Comment by Kwoth** [comment]
Will this going to be fixed?

**Comment by RogerSchmidlin** [comment]
I really like your library, because it makes my programming easier. But I can't use it because I am not able to used it for EVERY video, see in posts above. So I was wondering:
- is there a workaround for this
- are you trying to solve this problem?
- is it solvable?
- what is the future of YoutubeExtractor?
Thanks for your work so far

**Comment by RogerSchmidlin** [comment]
The extraction of the video link finishes. But when passing the link to the MediaPlayer I get following exceptions: "KnoxVpnUidStorageknoxVpnSupported API value returned is false"

**Comment by new01bie** [comment]
try MyToolkit instead

**Comment by RogerSchmidlin** [comment]
trying MyToolkit to do what? Have you solved the problem with loading the Vevo videos? Have you also tried to find a way to download them?
