### ISSUE TITLE
No Audio on some videos. link attached

### ISSUE THREAD

**Issue by rathin1980** [flagbug/YoutubeExtractor#89]
some of the movie trailers does not have an audio track in the downloaded file. only video. 
here is a link to the trailer that I tried with the example project that is inside the solution.
http://www.youtube.com/watch?v=Qwu51SYfQQs

**Comment by DarkTussin** [comment]
I'm pretty sure the example uses 360p because youtube saves the audio as a separate file for every HQ video (everything above 360p basically). 

It would be nice if this was stated somewhere, but FlagBug did say that he didn't want to maintain an ffmpeg wrapper.

I'm currently working on a program that will download HQ audio from youtube, so I have switched to finding the VideoInfo that contains a "0" resolution (the DASH audio files). I think you will have to use an ffmpeg wrapper if you want to merge the dash audio with the HQ video download.
